services:
  nginx:
    container_name: app_nginx
    build:
      context: ./docker
      dockerfile: nginx/Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - php
    ports:
      - "8080:80"
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./app:/app
      - ~/.composer-docker/cache:/root/.composer/cache
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.4.6
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "33061:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: on-failure
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    restart: always
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
