version: 3

tasks:
  # docker
  build:
    cmds:
      - docker compose up --build -d
  up:
    cmds:
      - docker compose up -d
  down:
    cmds:
      - docker compose down
  down-v:
    cmds:
      - docker compose down --remove-orphans --volumes
  restart:
    cmds:
      - task: down
      - task: up
  destroy:
    cmds:
      - docker compose down --rmi all --volumes --remove-orphans

  # common helpers
  dump-autoload:
    cmd: docker compose exec php composer dump-autoload
  csf:
    cmd: docker compose exec php ./vendor/bin/php-cs-fixer fix
  migrate:
    cmd: docker compose exec php bin/console doctrine:migrations:migrate
  fresh:
    cmd: docker compose exec php bin/console doctrine:migrations:migrate first
  bash:
    cmd: docker compose exec php bash
  consume:
    cmd: docker compose exec php bin/console messenger:consume --all
  fixtures:
    cmd: docker compose exec php bin/console doctrine:fixtures:load --append

  #testing
  tests:
    cmd: docker compose exec php bin/phpunit --testdox

  # asset-map:compile
  ams:
    cmds:
      - 'rm -rf app/public/assets'
      - docker compose exec php bin/console asset-map:compile

  # helpers with args
  php:
    cmd: docker compose exec php {{.c}}
  composer:
    cmd: docker compose exec php composer {{.c}}
  console:
    cmd: docker compose exec php bin/console {{.c}}
  cs-fixer:
    cmd: docker compose exec php ./vendor/bin/php-cs-fixer {{.c}}

  # install / init
  install:
    cmds:
      - task: prepare-env
      - task: build
      - task: permissions
      - docker compose exec php composer create-project symfony/skeleton .
      #      - docker compose exec php chmod -R 777 storage bootstrap/cache
      - task: permissions
  init:
    cmds:
      - task: prepare-env
      - task: build
      - docker compose exec php composer install

  # other
  permissions:
    cmds:
      - 'sudo chown $USER:$USER app'
  prepare-env:
    cmd: 'cp .env.example .env'

  default:
    - task: up